version: '3.10'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis-server:6379
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    hostname: redis-server
