AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ConnpassApiKey:
    Type: String
    Description: "API key for Connpass integration"

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fastapi-lambda
      Handler: app.main.lambda_handler
      Runtime: python3.10
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          CONNPASS_API_KEY: !Ref ConnpassApiKey
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /
            Method: ANY
