metadata:
  title: 'Yamanashi Tech Events API'
  description: 'This is an API for Tech events in Yamanashi prefecture.'
  version: '1.8.9'

api_client:
  user_agent: 'YamanashiTechEventAPI/{version} (+https://github.com/yuukis/yamanashi-event-api)'

recent_days: 120

scope:
  prefecture:
    - '山梨県'

  connpass:
    - subdomain: 'jagyamanashi' # 日本Androidの会 山梨支部
    - subdomain: 'coderdojokofu' # 子ども向けプログラミングクラブ コーダー道場甲府
    - subdomain: 'redmine-plugin-ymanasi' # Redmineプラグインもくもく会 山梨
    - subdomain: 'shingenpy' # shingen.py
    - subdomain: 'coderdojo-hokuto' # 子どものためのプログラミングクラブ CoderDojo北杜
    - subdomain: 'coderdojo-nirasaki' # 子どものためのプログラミングクラブ CoderDojo韮崎
    - subdomain: 'yamanashi-it' # 山梨IT同好会(仮)
    - subdomain: 'fujimokumokukai' # 富士もくもく会
    - subdomain: 'yamanashi-web' # 山梨Web勉強会
    - subdomain: 'yamanashi-spa' # 山梨SPA
    - subdomain: 'gdg-yamanashi' # GDG Yamanashi
    - subdomain: 'kainokuni' # 甲斐国もくもく会
    - subdomain: 'jaws-ug-yamanashi' # JAWS-UG山梨
    - subdomain: 'houtoupm' # Houtou.pm
    - subdomain: 'aibase' # AI BASE
    - subdomain: 'kofurb' # Kofu.rb
    - subdomain: 'ai-meetup' # 東京-山梨 AI ミートアップ
    - subdomain: 'yamanashi-encareer' # やまなしエンxキャリ（Engineer × Career）
    - subdomain: 'techmujin' # テック無尽
    - subdomain: 'ura-techmujin' # 裏テック無尽
    - subdomain: 'soracomug-tokyo' # SORACOM UG 山梨
      title_keyword: '山梨'
      key: 'soracomug-yamanashi'
      name: 'SORACOM UG 山梨'

  icalendar:
    - key: 'yamanashi-wordpress-meetup'
      name: 'Yamanashi WordPress Meetup'
      image_url: null
      group_url: https://www.meetup.com/ja-JP/yamanashi-wordpress-meetup/
      ical_url: https://www.meetup.com/ja-JP/Yamanashi-WordPress-Meetup/events/ical/

  archives:
    - url:
        - https://yuukis.github.io/yamanashi-event-archive/index.json
