name: DeployToAWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check required secrets
        run: |
          missing=""
          [ -z "${{ secrets.CONNPASS_API_KEY }}" ] && missing="${missing} CONNPASS_API_KEY"
          [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ] && missing="${missing} AWS_ACCESS_KEY_ID"
          [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ] && missing="${missing} AWS_SECRET_ACCESS_KEY"

          if [ -n "$missing" ]; then
            echo "Missing required secrets:${missing}"
            echo "Skipping."
            exit 0
          fi

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Set AWS Region
        run: echo "AWS_DEFAULT_REGION=ap-northeast-1" >> $GITHUB_ENV

      - name: Build with SAM
        run: sam build

      - name: Deploy with SAM
        run: |
          sam deploy --stack-name eventapi-stack \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --resolve-s3 \
            --force-upload \
            --no-confirm-changeset --no-fail-on-empty-changeset \
            --parameter-overrides ConnpassApiKey=${{ secrets.CONNPASS_API_KEY }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
