name: DockerHub

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check required secrets
        run: |
          missing=""
          [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] && missing="${missing} DOCKERHUB_USERNAME"
          [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ] && missing="${missing} DOCKERHUB_TOKEN"

          if [ -n "$missing" ]; then
            echo "Missing required secrets:${missing}"
            echo "Skipping."
            exit 0
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yuukis/yamanashi-event-api:${{ github.ref_name }}
      
      - name: Build and push Docker image
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: yuukis/yamanashi-event-api:latest
